parameters:
    news_images_directory: '%kernel.project_dir%/public/uploads/news'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/' # Entities are not services
            - '../src/Application/DTO/' # DTOs are not services
            - '../src/Domain/ValueObject/' # Value Objects are not services
            - '../src/Infrastructure/Doctrine/Entity/' # Entities are not services
            - '../src/Kernel.php'

    # Mapping manually the Repository Implementation to the Interface
    # Clean Architecture: The application logic requires the interface, 
    # but the container must provide the concrete implementation.
    App\Domain\Repository\NewsRepositoryInterface: '@App\Infrastructure\Doctrine\Repository\DoctrineNewsRepository'

    # Registering the Mapper explicitly if needed (though autowiring works)
    App\Infrastructure\Persistence\MySQL\NewsMapper: ~

    App\Infrastructure\Service\FileUploader:
        arguments:
            $targetDirectory: '%news_images_directory%'
